//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EcdsaSlyWallet struct {
	EcdsaAddress          string `sql:"primary_key"`
	OnChainAccountAddress string `sql:"primary_key"`
	OnChainPermissions    int32
}
