version: '3'

services:
  yip:
    image: leondroid/yip:0.1.6
    ports:
      - "8090:8080"
    volumes:
      - ./test_certs:/test_certs
      - ./yip.json:/yip.json

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

